### ISSUE TITLE
please document how to enable wol

### ISSUE THREAD

**Issue by pcfe** [linux-system-roles/network#150]
Wanting to switch from editing `/etc/sysconfig/network-scripts/ifcfg-…` I am wondering what the clean way to get
```
ETHTOOL_OPTS="wol g"
```
configured with _linux-system-roles / network_

The current README.md does not seem to contain either the string _wol_ or the string _wake_.

Since enabling wake on LAN (p|u|m|b|a|g|s|f|d) is a rather common procedure, it would be nice if this was covered in the documentation of the module.

**Comment by pcahyna** [comment]
I suspect it is not supported, support for some ethtool options was added in #115, but WOL does not seem to be among them. Documentation for those that are supported was added in that PR.

**Comment by pcfe** [comment]
yeah saw that and was surprised that WOL did not show up :-(

for now my workaround is

```yaml
    # enable WOL manually until https://github.com/linux-system-roles/network/issues/150 is fixed
    - name: "ensure Wake On LAN is enable for the upper network card"
      lineinfile:
        path:         /etc/sysconfig/network-scripts/ifcfg-enp2s0
        create:       false
        regexp:       '^ETHTOOL_OPTS= '
        insertafter:  '^TYPE=Ethernet'
        line:         'ETHTOOL_OPTS="wol g"'
```

not pretty but it does the job.
