### ISSUE TITLE
Support state:down persistent_state:absent for non-existent profile

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#188]
A configuration like

```yaml
network_connections:
   - name: non_existent
     state: down
     persistent_state: absent
```

should succeed instead of fail to allow idempotency/repeating this config to remove a profile (if it exists) without failing in later ansible runs.

Tasks:
- [x] Create an integration test
- [ ] Fix this for NM
- [ ] fix this for initscripts

Related bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1822777

**Comment by a-mere-peasant** [comment]
is something like this okay for the integration test ? 
```
---
- name: testing state down persistent_state absent for non existent profile
  hosts: all
  vars:
    network_connections:
       - name: non_existent
         state: down
         persistent_state: absent

  roles:
    - linux-system-roles.network
```
would fixing this mean not generating errors or ignoring them like #70 states ?
I think there should at least be a warning if in case there is a typo
