### ISSUE TITLE
MTU for vlan iface.

### ISSUE THREAD

**Issue by vkhatuwala** [linux-system-roles/network#19]
Hello,

I have setup a bond interface eg. bond0 and then I create a vlan on the bond0 eg. bond0.100, however the MTU for bond0 and its slave is correctly set to 9000, however I cannot set the MTU for the vlan interface and it defaults to 1500.

```
network_provider: nm
network_connections:
  # Bridge interface
  - name: br0
    state: up
    type: bridge
    interface_name: br0
    ip:
      dhcp4: no
      auto6: no
      gateway4: 1.0.0.1
      address:
        - "1.0.0.50/26"

  # Bond interface
  - name: bond0
    state: up
    type: bond
    interface_name: "bond0"
    bond:
      mode: 802.3ad
      miimon: 100
    mtu: 9000
    master: br0
    slave_type: bridge

  # Slave ethernet interfaces
  - name: em2
    state: up
    type: ethernet
    mtu: 9000
    interface_name: em2
    master: bond0

  - name: em1
    state: up
    type: ethernet
    mtu: 9000
    interface_name: em1
    master: bond0

  # VLAN on bond interface
  - name: bond0.100
    state: up
    type: vlan
    parent: bond0
    vlan_id: 100
    ip:
      address:
        - "10.10.10.51/24"
```

How can I solve this?

Thanks.

**Comment by tyll** [comment]
There was a bug in NM about setting MTU for VLANs that was fixed in the meantime: https://bugzilla.redhat.com/show_bug.cgi?id=1414901

@vkhatuwala can you please check if the bug is still present?

**Comment by pcahyna** [comment]
It is defnitely broken, here is my test playbook:
```yaml
network_connections:
  - name: eth1
    type: ethernet
    autoconnect: no
    state: up
    mtu: 1500
    ip:
      dhcp4: no
      auto6: no

  - name: eth1.90
    parent: eth1
    type: vlan
    vlan_id: 90
    mtu: 1500
    ip:
      address:
        - "10.50.0.32/24"
      gateway4: 10.50.0.1
```

I get the following error:
```
failure: created connection failed to normalize: nm-connection-error-quark:
connection.type: property is missing (6)
```
the `mtu` setting on `eth1` is not a problem, but on `eth1.90` it is.
