### ISSUE TITLE
ipv6.method ignore

### ISSUE THREAD

**Issue by petri3** [linux-system-roles/network#254]
Hello,
i need disable ipv6 only on one interface .
I would like obtain same effect that : "#nmcli connection modify eth0 ipv6.method ignore" on rhel 8
I look to python code, from line 950 to "master/library/network_connections.py"
`            if ip["auto6"]:
                s_ip6.set_property(NM.SETTING_IP_CONFIG_METHOD, "auto")
            elif addrs6:
                s_ip6.set_property(NM.SETTING_IP_CONFIG_METHOD, "manual")
            else:
                s_ip6.set_property(NM.SETTING_IP_CONFIG_METHOD, "ignore")`

Wich variable is needed for do that on the playbook ?

Thanks in advance,

**Comment by tyll** [comment]
This is an example to disable it:

```yaml
# SPDX-License-Identifier: BSD-3-Clause
---
- hosts: all
  vars:
    network_connections:
      - name: eth1
        type: ethernet
        ip:
          auto6: false
  roles:
    - linux-system-roles.network
...
```

Please note that you need to specify the full configuration for the profile since it is not supported to change only one attribute of a profile.

Does this answer your question?

**Comment by petri3** [comment]
It's work for obtain ipv6.method ignore. but not my expected :-(
my ansible variable: 
```
network_provider: nm
network_allow_restart: yes
network_connections:
  - name: eth0
    state: up
    type: ethernet
    #autoconnect: yes
    mac: "{{ ansible_default_ipv4.macaddress }}"
    mtu: xxxx
    zone: foo
    ip:
      dhcp4: no
      auto6: false
      address:
        - "x.x.x.x/xx"
      gateway4: x.x.x.x
      dns:
        - x.x.x.x
        - x.x.x.x
      dns_search:
        - foo.bar
```
after execute ansible with no error: 
i obtain; 

cat /etc/syscon/network-script/ifcfg-eth0
```
HWADDR=XX:XX:XX:XX:XX:XX
MTU=xxxx
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
ETHTOOL_OPTS="-K net0"
BOOTPROTO=none
IPADDR=x.x.x.x
PREFIX=xx
GATEWAY=x.x.x.x
DNS1=x.x.x.x
DNS2=x.x.x.x
DOMAIN="foo.bar"
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=no
NAME=eth0
UUID=xxxxxxxxxxxxxxxxxxxxxx
ONBOOT=yes
ZONE=foo
```
 check nmtui : ` IPv6 CONFIGURATION <Ignore>`
check nmcli  nmcli connection show eth0 :
