### ISSUE TITLE
Role not idempotent for infiniband interface

### ISSUE THREAD

**Issue by mjrasobarnett** [linux-system-roles/network#277]
Hello,
I've been trying out this role against a server that has both ethernet and infiniband interfaces, and I've found that the infiniband interface is continually updated on every run.

I am using the role with the following variables:
```
  roles:                                                                  
    - role: "network"                                                     
      network_provider: "{{ network_provider_os_default }}"              
      network_allow_restart: no                                          
      network_connections:                                               
        - name: 'em4'                                                    
          type: 'ethernet'                                               
          interface_name: 'em4'                                          
          state: 'up'                                                    
          ip:                                                            
            address:                                                                                                                                                                                                
              - "192.168.0.1/24"                                       
        - name: 'ib0'                                                    
          type: 'infiniband'                                             
          state: 'up'                                                    
          interface_name: 'ib0'                                          
          ip:                                                            
            address:                                                     
              - "10.0.0.1/16"
```

The remote host is a RHEL7.8 system, and I'm using the latest tag of this repo, v1.2.0 with ansible 2.9.10.

The 'Configure networking connection profiles' task always shows as changed, with the following in the stderr returned:

```
  stderr: |-
    [005] <info>  #0, state:up persistent_state:present, 'em4': connection em4, d1e89262-2a9a-4a05-b551-f867a1dee0a4 already up to date
    [006] <info>  #1, state:up persistent_state:present, 'ib0': update connection ib0, ef06f091-c51b-43fa-91e8-b3691a085506
    [007] <info>  #0, state:up persistent_state:present, 'em4': up connection em4, d1e89262-2a9a-4a05-b551-f867a1dee0a4 skipped because already active
    [008] <info>  #1, state:up persistent_state:present, 'ib0': up connection ib0, ef06f091-c51b-43fa-91e8-b3691a085506 (is-modified)
    [009] <info>  #1, state:up persistent_state:present, 'ib0': connection reapplied
  stderr_lines: <omitted>
```

I've been attempting to trace the behaviour through the module code on the remote host, and I can see that the key check is inside the 'run_action_present' function of the Cmd_nm class, where,
self.nmutil.connection_compare is returning false.

I've been trying to observe why this is, but it's becoming difficult as I think this function is then using python bindings from NetworkManager itself to compare the two connection objects, and I haven't been able to follow what happens at this point.

I was wondering if someone might be able to offer any guidance on what might be the issue here, and how I could observe the state perhaps to see why it keeps trying to update this IB connection continuously?

Many thanks,
Matt
