### ISSUE TITLE
Failures in the collection converted tests

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/network#287]
Collections conversion tool for linux-system-roles converts the linux-system-roles tree structure to the collection tree structure and replaces the role value with FQCN in the yaml files as well as in the modules/module_utils.

This is just a heads-up; there are 2 cases the conversion tool cannot support.

1. direct access expecting the roles tree structure
```
tests/tests_unit.yml
- hosts: all
  name: execute python unit tests
  tasks:
    - name: Copy python modules
      copy:
        src: "{{ item }}"
        dest: /tmp/test-unit-1/
        local_follow: false
      loop:
        - ../library/network_connections.py
        - unit/test_network_connections.py
        - ../module_utils/network_lsr
```

2. requires git repository
```
tests/tests_integration_pytest.yml
- name: Run Pytest tests
  hosts: all
  vars:
    - rundir: /run/system-roles-test
  tasks:
    - file:
        state: directory
        path: "{{ rundir }}"
        recurse: true

    - command: git rev-parse --show-toplevel
      register: git_top_directory
      delegate_to: localhost
```
