### ISSUE TITLE
Providing both interface_name and mac fails.

### ISSUE THREAD

**Issue by kristvanbesien** [linux-system-roles/network#314]
Hello,

I have the following in my network_connections.

```
network_connections:
- name: "System int0"
    state: up
    type: ethernet
    interface_name: int0
    mac: "{{ ansible_int0.macaddress }}"
    master: "Bond bond0
```
This results in this error:

```
[WARNING]: [001] <error> #1, state:up persistent_state:present, 'System int0': profile specifies interface_name 'int0' and mac
'ac:1f:6b:c4:bc:06' but no such interface exists
fatal: [mgg-mgt001-fra5.mgg.local]: FAILED! => {"_invocation": {"module_args": {"__debug_flags": "", "connections": [{"bond": {"miimon": 100, "mode": "802.3ad"}, "interface_name": "bond0", "ip": {"address": ["10.123.210.131/26"], "auto6": false, "dhcp4": false, "dns": ["10.0.80.11", "10.0.80.12"], "dns_search": "mgg.local", "route": [{"gateway": "10.123.210.129", "metric": 301, "network": "10.0.0.0", "prefix": 8}, {"gateway": "10.123.210.129", "metric": 301, "network": "161.26.0.0", "prefix": 16}, {"gateway": "10.123.210.129", "metric": 301, "network": "166.8.0.0", "prefix": 16}]}, "name": "Bond bond0", "state": "up", "type": "bond"}, {"interface_name": "int0", "mac": "ac:1f:6b:c4:bc:06", "master": "Bond bond0", "name": "System int0", "state": "up", "type": "ethernet"}, {"interface_name": "int2", "mac": "ac:1f:6b:c4:bc:06", "master": "Bond bond0", "name": "System int2", "state": "up", "type": "ethernet"}, {"name": "VLAN 1159", "persistent_state": "absent", "state": "down"}, {"interface_name": "bond0.1162", "ip": {"address": ["10.123.231.146/29"], "auto6": false, "dhcp4": false, "route": [{"gateway": "10.123.231.145", "metric": 301, "network": "10.201.142.0", "prefix": 24}]}, "name": "VLAN 1162", "parent": "Bond bond0", "state": "up", "type": "vlan", "vlan_id": 1162}], "force_state_change": false, "ignore_errors": false, "provider": "nm"}}, "changed": false, "msg": "error: profile specifies interface_name 'int0' and mac 'ac:1f:6b:c4:bc:06' but no such interface exists", "stderr": "[001] <error> #1, state:up persistent_state:present, 'System int0': profile specifies interface_name 'int0' and mac 'ac:1f:6b:c4:bc:06' but no such interface exists\n", "stderr_lines": ["[001] <error> #1, state:up persistent_state:present, 'System int0': profile specifies interface_name 'int0' and mac 'ac:1f:6b:c4:bc:06' but no such interface exists"]}
```

However this interface does exist:

```
[root@mgg-mgt001-fra05 int0]# ip link show int0
2: int0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether ac:1f:6b:c4:bc:06 brd ff:ff:ff:ff:ff:ff
```
Target is a RHEL8 system. What is going on here?

**Comment by kristvanbesien** [comment]
I suspect that it might just be that the MAC address in the config is lowercase, whereas nmcli uses uppercase. It might be usefull to the mac address case insensitive.

**Comment by kristvanbesien** [comment]
It appears not to be related to upercase/lowercase
So this issue still needs fixing.

**Comment by kristvanbesien** [comment]
I am running in the same issue on rhel7. Giving both an interface name and a MAC fails. 
Is there any chance that this is going to be addressed at one time?

**Comment by thom311** [comment]
the error message comes from https://github.com/linux-system-roles/network/blob/main/library/network_connections.py#L1824, but it's not clear why.

Can you edit the printed message to also show `li_mac` and `li_ifname`?

**Comment by kristvanbesien** [comment]
This is the network config I am using:


```
# The Network configuration. This is consumed by the linux-system-roles.network role
network_provider: initscripts
network_connections:
     
  - name: "bond1"
    persistent_state: absent
   
  - name: "bond0"
    state: up
    type: bond
    bond:
      mode: 802.3ad
      miimon: 100
    interface_name: bond0
    ip:
      dhcp4: no
      address:
      - "{{ private_ip_cidr}}"
      gateway4: "{{ private_network_gateway }}"
      route: "{{ private_routes }}"
      dns: "{{ dns_servers }}"
      dns_search: "{{ dns_search }}"
      
 

  - name: "int0"
    state: up
    type: ethernet
    interface_name: int0
    mac: "{{ ansible_int0.macaddress }}"
    master: "bond0"

  - name: "int2"
    state: up
    type: ethernet
    interface_name: int2
    mac: "{{ ansible_int2.macaddress }}"
    master: "bond0"
     
    
  - name: "bond0.{{ storage_vlan }}"
    state: up
    type: vlan
    parent: "bond0"
    interface_name: "bond0.{{ storage_vlan }}"
    vlan_id: "{{ storage_vlan }}"
    ip:
      dhcp4: no
      address:
      - "{{ storage_ip_cidr }}"
      route: "{{ storage_routes }}"
```
And here the output (run through jq for clarity...)

```
fatal: [XXX]: FAILED! => {
  "_invocation": {
    "module_args": {
      "__debug_flags": "",
      "connections": [
        {
          "name": "bond1",
          "persistent_state": "absent"
        },
        {
          "bond": {
            "miimon": 100,
            "mode": "802.3ad"
          },
          "interface_name": "bond0",
          "ip": {
            "address": [
              "10.13.25.224/26"
            ],
            "dhcp4": false,
            "dns": [
              "10.123.210.167"
            ],
            "dns_search": "XXX",
            "gateway4": "10.13.25.193",
            "route": [
              {
                "gateway": "10.13.25.193",
                "metric": 301,
                "network": "10.0.0.0",
                "prefix": 8
              },
              {
                "gateway": "10.13.25.193",
                "metric": 301,
                "network": "161.26.0.0",
                "prefix": 16
              },
              {
                "gateway": "10.13.25.193",
                "metric": 301,
                "network": "166.8.0.0",
                "prefix": 16
              }
            ]
          },
          "name": "bond0",
          "state": "up",
          "type": "bond"
        },
        {
          "interface_name": "int0",
          "mac": "3c:fd:fe:87:56:98",
          "master": "bond0",
          "name": "int0",
          "state": "up",
          "type": "ethernet"
        },
        {
          "interface_name": "int2",
          "mac": "3c:fd:fe:87:56:98",
          "master": "bond0",
          "name": "int2",
          "state": "up",
          "type": "ethernet"
        },
        {
          "interface_name": "bond0.1264",
          "ip": {
            "address": [
              "10.13.33.51/28"
            ],
            "dhcp4": false,
            "route": [
              {
                "gateway": "10.13.33.49",
                "metric": 301,
                "network": "10.201.142.0",
                "prefix": 24
              }
            ]
          },
          "name": "bond0.1264",
          "parent": "bond0",
          "state": "up",
          "type": "vlan",
          "vlan_id": 1264
        }
      ],
      "force_state_change": false,
      "ignore_errors": false,
      "provider": "initscripts"
    }
  },
  "changed": false,
  "msg": "error: profile specifies interface_name 'int0' and mac '3c:fd:fe:87:56:98' but no such interface exists",
  "stderr": "[001] <error> #2, state:up persistent_state:present, 'int0': profile specifies interface_name 'int0' and mac '3c:fd:fe:87:56:98' but no such interface exists\n",
  "stderr_lines": [
    "[001] <error> #2, state:up persistent_state:present, 'int0': profile specifies interface_name 'int0' and mac '3c:fd:fe:87:56:98' but no such interface exists"
  ]
}
```

As I have already indicated interfaces with the names and macs indicated do in fact exist.

I can leave of the name, and that does allow the playbook to run. But this breaks the system, as upon the next reboot int0 will have been renamed eth0, and the system becomes inaccessible. 

Currently I fix this by adding the HWADDR line afterwards. using lineinfile on systems with initscripts, and using an nmcli invocaiton where networkmanager is used, but that is not what you want.

**Comment by tyll** [comment]
From the output:
```
          "interface_name": "int0",
          "mac": "3c:fd:fe:87:56:98",
[...]
          "interface_name": "int2",
          "mac": "3c:fd:fe:87:56:98",
```

Both interfaces use the same MAC address, so I guess the error message that int0 does not use this MAC address is correct. Therefore I close this issue. If the inventory has different addresses for the interfaces and you can still reproduce it, please re-open this with a complete playbook that can reproduce the issue. Not sure about the correct terms, the issue might be that the MAC addresses appear to be the same because of the bond mode but the permanent hardware address is the one that needs to be specified here, I believe.

Thank you.

**Comment by GR360RY** [comment]
The problem can be easily reproduced by testing the configuration on device with vlan configured. `interface_name` is a required parameter for a vlan parent interface. The failure occurs in `SysUtil.link_info_find(mac=connection["mac"])` which would return a VLAN interface by mac instead of the parent interface.

Here is the output of the module with modified log_fatal:

```
                if li_mac and li_ifname and li_mac != li_ifname:
                    self.log_fatal(
                        idx,
                        "profile specifies interface_name '%s' and mac '%s' but no "
                        "such interface exists"
                        % (li_mac, li_ifname),
                    )
```

```
[WARNING]: [001] <error> #8, state:up persistent_state:present, 'sfn0p2': li_mac: {'ifindex': 11, 'perm-address': '00:00:00:00:00:00', 'ifname': 'sfn0p2.2333', 'address': '00:0f:53:49:f0:a3'}, li_ifname:
{'ifindex': 7, 'perm-address': '00:0f:53:49:f0:a3', 'ifname': 'sfn0p2', 'address': '00:0f:53:47:f0:a1'}
```

For me the workaround was to update the connection variables of type ethernet with `check_iface_exists: false`. This parameter is not available in docs, but works as a charm. See

```
    def run_prepare(self):
        for idx, connection in enumerate(self.connections):
            if "type" in connection and connection["check_iface_exists"]:
```

**Comment by liangwen12year** [comment]
@GR360RY , can you share the inventory file and the complete playbook here for us to reproduce the issue and help to debug?

**Comment by TJuberg** [comment]
@liangwen12year

Ran into this issue myself first in rhel-system-roles.network 1.16.4, and verified today with linux-system-roles.network 1.17.0

My play is simplistic:
```yaml
    - name: Ethernet connection profile settings using network_connections
      ansible.builtin.include_role:
      #   name: rhel-system-roles.network
      name: linux-system-roles.network
      loop: "{{ network_connections }}"
      when: network_connections is defined
```
The host vars excluding the primary interface are:
```yaml
network_connections:
  - name: 00-ens224-TRUNK
    state: up
    persistent_state: present
    autoconnect: true
    type: ethernet
    interface_name: ens224
    mac: 00:50:56:B0:81:92
    ip:
      dhcp4: false
      auto6: false

  - name: ens224.3732
    state: up
    persistent_state: present
    type: vlan
    parent: 00-ens224-TRUNK
    vlan:
      id: 3732
    autoconnect: true
    ip:
      auto_gateway: false
      ipv6_disabled: true
      gateway4: 10.10.0.1
      address: 10.10.0.6/24
      dhcp4: false
      auto6: false
```

The  actual error ffrom the play:
```
TASK [linux-system-roles.network : Configure networking connection profiles] ***
[WARNING]: [001] <error> #2, state:up persistent_state:present, '00-ens224-TRUNK': profile specifies interface_name 'ens224' and mac
'00:50:56:b0:81:92' but no such interface exists
```

The error is emitted from network_connections.py
https://github.com/linux-system-roles/network/blob/560173b5bf97d901f42cd11054f160af329e22cb/library/network_connections.py#L2176

I modified the output to show the values of li_mac and li_ifname:
```python
                if li_mac and li_ifname and li_mac != li_ifname:
                    self.log_fatal(
                        idx,
                        "profile specifies interface_name '%s' and mac '%s' but no "
                        "such interface exists. Debug: li_mac '%s' li_ifname '%s'"
                        % (connection["interface_name"], connection["mac"], li_mac, li_ifname),
                    )
```

The logged warning is now
```
[WARNING]: [001] <error> #2, state:up persistent_state:present, '00-ens224-PUB-
PROD-TRUNK': profile specifies interface_name 'ens224' and mac
'00:50:56:b0:81:92' but no such interface exists. Debug: li_mac '{'ifindex': 4,
'ifname': 'ens224.3732', 'address': '00:50:56:b0:81:92', 'perm-address':
'00:00:00:00:00:00'}' li_ifname '{'ifindex': 3, 'ifname': 'ens224', 'address':
'00:50:56:b0:81:92', 'perm-address': '00:50:56:b0:81:92'}'
```

For easier reading:
```json
{
  "interface1": {
    "ifindex": "4",
    "ifname": "ens224.3732",
    "address": "00:50:56:b0:81:92",
    "perm-address": "00:00:00:00:00:00"
  },
  "li_ifname": {
    "ifindex": "3",
    "ifname": "ens224",
    "address": "00:50:56:b0:81:92",
    "perm-address": "00:50:56:b0:81:92"
  }
}
```

Walking trough the code one ends up at
https://github.com/linux-system-roles/network/blob/560173b5bf97d901f42cd11054f160af329e22cb/library/network_connections.py#L165

and

https://github.com/linux-system-roles/network/blob/560173b5bf97d901f42cd11054f160af329e22cb/library/network_connections.py#L170

Which essentially does:
```
cat /sys/class/net/ens224/address
00:50:56:b0:81:92

cat /sys/class/net/ens224.3732/address
00:50:56:b0:81:92

ethtool -P ens224
Permanent address: 00:50:56:b0:81:92

ethtool -P ens224.3732
Permanent address: not set
```

From what I can tell this is failing because it is comparing a VLAN-interface which will never have a permanent MAC address to my knowledge, against the TRUNK interface which does have a permanent MAC address.

The logic needs to be improved to handle virtual interfaces without a permanent MAC ideally.
