### ISSUE TITLE
Does this role work on other distributions like Debian or Ubuntu?

### ISSUE THREAD

**Issue by Hoeze** [linux-system-roles/network#357]
Hi, what are the dependencies of this role?
Can I use it to configure network distribution-independently?

**Comment by thom311** [comment]
The role currently supports two backends (`provider`): NetworkManager and initscripts.

Debian/Ubuntu doesn't use initscripts, so that backend cannot work.

But if you use NetworkManager for network configuration on Debian/Ubuntu, then the role is supposed to work just the same. If it doesn't, it would be a bug.

**Comment by Hoeze** [comment]
Thanks a lot @thom311, then I'll definitely try this!

**Comment by thom311** [comment]
I don't know how much this is tested. So hopefully it works just fine.

If not, please report back! It is supposed to work. Thank you.

**Comment by thom311** [comment]
And for the record: theoretically other providers/backends could be added too (e.g. systemd-networkd). But that requires somebody to contribute them. Patches welcome!

**Comment by parisholley** [comment]
does not work, ubuntu expects the package "network-manager" , not "NetworkManager"

**Comment by parisholley** [comment]
for anyone who hits this in a future, you need at least ubuntu 20.04 (old versions have an old version of libnm which is not compatible with python code). the role also doesn't update apt-cache, so you'll need some playbook which triggers it before this role gets invoked. here is what I did to make it work:

```yaml
---
- name: Update apt cache
  hosts: all
  tasks:
    - name: Install network manager
      apt:
        name: network-manager
        update_cache: yes
        state: present

- name: Provision networking
  hosts: all
  roles:
    - name: linux-system-roles.network
      vars:
        network_provider: nm
        network_packages:
          - network-manager
          - gir1.2-nm-1.0
        network_connections:
```
