### ISSUE TITLE
ipv6.dns-search not allowed for method = ignore

### ISSUE THREAD

**Issue by codeRhein** [linux-system-roles/network#418]
Hello! We found out that `ipv6.dns-search` is not allowed for `ignore` as `ipv6.method` for a `bridge` interface.  

To reproduce (on `centos8` with `NM`):
```
---
- hosts: localhost
  vars:
    network_connections:
      - name: br-example
        type: bridge
        ip:
          dhcp4: false
          auto6: false
          dns:  8.8.8.8
          dns_search: google.com
          address:
            - 10.2.2.77/26
	state: up
  roles:
    - network
```

The error: 
```
TASK [network : Configure networking connection profiles] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"_invocation": {"module_args": {"__debug_flags": "", "connections": [{"ip": {"address": ["10.2.2.77/26"], "auto6": false, "dhcp4": false, "dns": "8.8.8.8", "dns_search": "google.com"}, "name": "br-admin", "state": "up", "type": "bridge"}], "force_state_change": false, "ignore_errors": false, "provider": "nm"}}, "changed": false, "msg": "fatal error: created connection failed to normalize: nm-connection-error-quark: ipv6.dns-search: this property is not allowed for 'method=ignore' (7)", "stderr": "\n", "stderr_lines": [""]}
```

Please help, thank you!
