### ISSUE TITLE
[RFE] Ability to manage or modify based on hardware address

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/network#44]
Need the ability to execute operations based only on hardware address or naming (mac, pci address, kernel device name) as opposed to only by "connection profile" name, which is very weak when using initscript style naming.

For example, in my hardware inventory, I know all of my MAC addrs, but possibly due to inconsistent net device naming or other reasons, the connection names are inconsistent.

Need the ability to [down/up, delete/rename conn name, modify attributes] of any NICs based on MAC or pci addr

**Comment by tabowling** [comment]
Here is an example playbook.

```
---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    network_connections:

      - name: net0  # Can we rename the primary interface?!?!?!
        state: present
        type: ethernet
#        interface_name: eth0
        mac: "{{ hostvars[inventory_hostname].net0_mac }}"
        autoconnect: yes
        ip:
          dhcp4: yes
          auto6: no

      - mac: "{{ hostvars[inventory_hostname].net0_mac }}"
        state: absent
        # need to ensure this interface is completely unused 
        # before reusing it for something else.
  roles:
    - role: rhel-system-roles.network
#    - role: linux-system-roles.network

```

**Comment by tabowling** [comment]
Ansible facts provides all details of all net configurations accessible via variables at runtime.  Here is an example playbook that accesses them and outputs them to the console.

```
---

- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: find interface facts
      debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_%s' | format(item)] }}"
      with_items: "{{ ansible_interfaces }}"
```

Here are some other helpful commands
```
ansible rhel74-test -m setup -a 'gather_subset=network'
ansible rhel74-test -m setup -a 'gather_subset=network filter=ansible_interfaces'
ansible rhel74-test -m setup -a 'gather_subset=network' |grep -e ansible_e -e macaddr -e hostname -e device

```

**Comment by tabowling** [comment]
Here is an example of how I am managing the inventory locally in my /etc/ansible/hosts file.  This could be similar to how Ansible Tower or Satellite might keep an inventory of the nodes they manage.

This is how I was passing the MAC in as a variable in the first playbook example I submitted.

```
all:
  hosts:
    util6vm:
      net0_mac: "52:54:00:64:c0:fd"
      net1_mac: "52:54:00:23:b2:28"
      net2_mac: "52:54:00:5e:bc:e9"
      net3_mac: "52:54:00:46:55:59"
      net4_mac: "52:54:00:b5:4c:8f"
      net5_mac: "52:54:00:97:7c:96"
      webbond_ip: '192.168.75.231/24'
      webbond-link1: net2_mac
      webbond-link2: net4_mac
      dbbond_ip: '192.168.75.241/24'
      dbbond-link1: net3_mac
      dbbond-link2: net5_mac
    util7vm:
      net0_mac: "52:54:00:92:34:c8"
      net1_mac: "52:54:00:92:37:36"
      net2_mac: "52:54:00:61:bf:85"
      net3_mac: "52:54:00:3f:a4:d8"
      net4_mac: "52:54:00:d9:8c:d7"
      net5_mac: "52:54:00:a0:6e:f2"
      webbond_ip: '192.168.75.232/24'
      webbond-link1: net2_mac
      webbond-link2: net4_mac
      dbbond_ip: '192.168.75.242/24' 
      dbbond-link1: net3_mac
      dbbond-link2: net5_mac
```
