### ISSUE TITLE
Creating a bond vlan bridge at the same time

### ISSUE THREAD

**Issue by avbg** [linux-system-roles/network#487]
Hello.
My network_connections look like this:
```
network_connections:
  - name: bond0
    state: up
    type: bond
    interface_name: bond0
    bond:
      mode: active-backup
      miimon: 100

  - name: enp7s0f0
    state: up
    type: ethernet
    interface_name: enp7s0f0
    controller: bond0
    port_type: bond

  - name: enp7s0f1
    state: up
    type: ethernet
    interface_name: enp7s0f1
    controller: bond0
    port_type: bond

  - name: vlan10
    state: up
    type: vlan
    parent: bond0
    vlan_id: 10
    ip:
      dhcp4: no
      auto6: no

  - name: vlan20
    state: up
    type: vlan
    parent: bond0
    vlan_id: 20
    ip:
      dhcp4: no
      auto6: no
      
  - name: mgmt
    state: up
    type: bridge
    interface_name: mgmt
    ip:
      address: "192.168.2.11/24"
      gateway4: "192.168.2.5"
      auto6: no
      dns:
        - 8.8.8.8
  - name: mgmt-vlan10
    interface_name: vlan10
    state: up
    type: ethernet
    controller: mgmt
    port_type: bridge

  - name: vmbr0
    state: up
    type: bridge
    interface_name: vmbr0
    ip:
      dhcp4: no
      auto6: no

  - name: vmbr0-vlan20
    state: up
    type: ethernet
    interface_name: vlan20
    controller: vmbr0
    port_type: bridge      

```
I'm getting this error:
```
[WARNING]: [001] <error> #6, state:up persistent_state:present, 'mgmt-vlan10': profile specifies interface_name 'vlan10' but no such interface exists
fatal: [ispv11]: FAILED! => {
    "_invocation": {
        "module_args": {
            "__debug_flags": "",
            "__header": "#\n# Ansible managed\n#\n",
            "connections": [
                {
                    "bond": {
                        "miimon": 100,
                        "mode": "active-backup"
                    },
                    "interface_name": "bond0",
                    "name": "bond0",
                    "state": "up",
                    "type": "bond"
                },
                {
                    "controller": "bond0",
                    "interface_name": "enp7s0f0",
                    "name": "enp7s0f0",
                    "port_type": "bond",
                    "state": "up",
                    "type": "ethernet"
                },
                {
                    "controller": "bond0",
                    "interface_name": "enp7s0f1",
                    "name": "enp7s0f1",
                    "port_type": "bond",
                    "state": "up",
                    "type": "ethernet"
                },
                {
                    "ip": {
                        "auto6": false,
                        "dhcp4": false
                    },
                    "name": "vlan10",
                    "parent": "bond0",
                    "state": "up",
                    "type": "vlan",
                    "vlan_id": 10
                },
                {
                    "ip": {
                        "auto6": false,
                        "dhcp4": false
                    },
                    "name": "vlan20",
                    "parent": "bond0",
                    "state": "up",
                    "type": "vlan",
                    "vlan_id": 20
                },
                {
                    "interface_name": "mgmt",
                    "ip": {
                        "address": "192.168.2.11/24",
                        "auto6": false,
                        "dns": [
                            "8.8.8.8"
                        ],
                        "gateway4": "192.168.2.5"
                    },
                    "name": "mgmt",
                    "state": "up",
                    "type": "bridge"
                },
                {
                    "controller": "mgmt",
                    "interface_name": "vlan10",
                    "name": "mgmt-vlan10",
                    "port_type": "bridge",
                    "state": "up",
                    "type": "ethernet"
                },
                {
                    "interface_name": "vmbr0",
                    "ip": {
                        "auto6": false,
                        "dhcp4": false
                    },
                    "name": "vmbr0",
                    "state": "up",
                    "type": "bridge"
                },
                {
                    "controller": "vmbr0",
                    "interface_name": "vlan20",
                    "name": "vmbr0-vlan20",
                    "port_type": "bridge",
                    "state": "up",
                    "type": "ethernet"
                }
            ],
            "force_state_change": false,
            "ignore_errors": false,
            "provider": "nm"
        }
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "__debug_flags": "",
            "__header": "#\n# Ansible managed\n#\n",
            "connections": [
                {
                    "bond": {
                        "miimon": 100,
                        "mode": "active-backup"
                    },
                    "interface_name": "bond0",
                    "name": "bond0",
                    "state": "up",
                    "type": "bond"
                },
                {
                    "controller": "bond0",
                    "interface_name": "enp7s0f0",
                    "name": "enp7s0f0",
                    "port_type": "bond",
                    "state": "up",
                    "type": "ethernet"
                },
                {
                    "controller": "bond0",
                    "interface_name": "enp7s0f1",
                    "name": "enp7s0f1",
                    "port_type": "bond",
                    "state": "up",
                    "type": "ethernet"
                },
                {
                    "ip": {
                        "auto6": false,
                        "dhcp4": false
                    },
                    "name": "vlan10",
                    "parent": "bond0",
                    "state": "up",
                    "type": "vlan",
                    "vlan_id": 10
                },
                {
                    "ip": {
                        "auto6": false,
                        "dhcp4": false
                    },
                    "name": "vlan20",
                    "parent": "bond0",
                    "state": "up",
                    "type": "vlan",
                    "vlan_id": 20
                },
                {
                    "interface_name": "mgmt",
                    "ip": {
                        "address": "192.168.2.11/24",
                        "auto6": false,
                        "dns": [
                            "8.8.8.8"
                        ],
                        "gateway4": "192.168.2.5"
                    },
                    "name": "mgmt",
                    "state": "up",
                    "type": "bridge"
                },
                {
                    "controller": "mgmt",
                    "interface_name": "vlan10",
                    "name": "mgmt-vlan10",
                    "port_type": "bridge",
                    "state": "up",
                    "type": "ethernet"
                },
                {
                    "interface_name": "vmbr0",
                    "ip": {
                        "auto6": false,
                        "dhcp4": false
                    },
                    "name": "vmbr0",
                    "state": "up",
                    "type": "bridge"
                },
                {
                    "controller": "vmbr0",
                    "interface_name": "vlan20",
                    "name": "vmbr0-vlan20",
                    "port_type": "bridge",
                    "state": "up",
                    "type": "ethernet"
                }
            ],
            "force_state_change": false,
            "ignore_errors": false,
            "provider": "nm"
        }
    },
    "msg": "error: profile specifies interface_name 'vlan10' but no such interface exists",
    "stderr": "[001] <error> #6, state:up persistent_state:present, 'mgmt-vlan10': profile specifies interface_name 'vlan10' but no such interface exists\n",
    "stderr_lines": [
        "[001] <error> #6, state:up persistent_state:present, 'mgmt-vlan10': profile specifies interface_name 'vlan10' but no such interface exists"
    ]
```
The vlan (enp7s0f0.10@enp7s0f0)  is already configured on the server through which I connect. Is it possible to set up a network through the described network_connections?
I want to get this configuration:
```
enp7s0f0 -        - vlan10 - mgmt
           bond0 
enp7s0f0 -        - vlan20 - vmbr0
```
The OS is Centos 7, ansible [core 2.12.2]

**Comment by richm** [comment]
> The OS is Centos 7, ansible [core 2.12.2]

I'm assuming the OS is the managed host OS?

What version of the network role are you using?

**Comment by avbg** [comment]
1) Yes
2) version 1.7.1

**Comment by tyll** [comment]
@thom311 @liangwen12year could you please take a look? 

@avbg I noticed this in the playbook:

```
  - name: vmbr0-vlan20
    state: up
    type: ethernet
    interface_name: vlan20
    controller: vmbr0
    port_type: bridge      
```
If this should define a vlan, it needs to be of type vlan with parent specifying bond0 and

```
vlan:
    id: 20
```

to specify the vlan ID.

**Comment by liangwen12year** [comment]
@tyll , sure, I will.

**Comment by liangwen12year** [comment]
@avbg , just wondered why the device type of vlan10 can be both vlan and ethernet above.

```
[root@ibm-p8-kvm-03-guest-02 ~]# ip -d a s  vlan10
16: vlan10@nm-bond: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN group default qlen 1000
    link/ether 56:1e:a3:d4:c8:1f brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 0 maxmtu 65535
    vlan protocol 802.1Q id 10 <REORDER_HDR> numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535  

[root@ibm-p8-kvm-03-guest-02 ~]# nmcli d
DEVICE       TYPE      STATE                                  CONNECTION    
vlan10       vlan      connected                              vlan10        
```

**Comment by tyll** [comment]
Good point @liangwen12year, so instead of 

```
  - name: vlan20
    state: up
    type: vlan
    parent: bond0
    vlan_id: 20
    ip:
      dhcp4: no
      auto6: no
  - name: vmbr0-vlan20
    state: up
    type: ethernet
    interface_name: vlan20
    controller: vmbr0
    port_type: bridge    
```

it needs to be:

```
  - name: vlan20
    state: up
    type: vlan
    parent: bond0
    controller: vmbr0
    port_type: bridge    
    vlan_id: 20
    ip:
      dhcp4: no
      auto6: no
```

So it seems to be wrong configuration, therefore I will close this issue. Please re-open it or file a new one, if necessary.
