### ISSUE TITLE
s390x z/vm qeth support

### ISSUE THREAD

**Issue by nirik** [linux-system-roles/network#489]
Greetings. 

We have some s390x z/vm instances running Fedora 35. 

They need: 

```
LAYER2=1
SUBCHANNELS=0.0.0900,0.0.0901,0.0.0902
NETTYPE=qeth
```

In order to see/use their network adapter. If we simply add this to the ifcfg-enc900, things work, but linux-system-roles/network says: 

```
TASK [linux-system-roles.network : Show stderr messages] ********************************************
Monday 04 April 2022  16:42:01 +0000 (0:00:01.048)       0:00:12.286 **********                     
Monday 04 April 2022  16:42:01 +0000 (0:00:01.048)       0:00:12.285 **********                     
ok: [buildvm-s390x-01.s390.fedoraproject.org] => {
    "__network_connections_result.stderr_lines": [
        "[003] <info>  #0, state:up persistent_state:present, 'enc900': update connection enc900, 470
c8f30-235f-4a2d-a9a4-8809b7a2b6a0",
        "[004] <info>  #0, state:up persistent_state:present, 'enc900': up connection enc900, 470c8f3
0-235f-4a2d-a9a4-8809b7a2b6a0 (is-modified)",
        "[005] <info>  #0, state:up persistent_state:present, 'enc900': connection reapply failed: fa
ilure to reapply checkpoint: nm-device-error-quark: Can't reapply changes to '802-3-ethernet.s390-sub
channels' setting (3): {'error': \"nm-device-error-quark: Can't reapply changes to '802-3-ethernet.s3
90-subchannels' setting (3)\", 'success': None}"
    ]

```

So I guess we need a way to pass this configuration as options? 
Happy to provide more info, etc.

**Comment by thom311** [comment]
the `connection reapply failed` message is not relevant. It only means the role needs to proceed with a `nmcli connection up` (after `nmcli device reapply` failed). That's normal.

what playbook did you use to test this? Since the role does not support s390 options, I don't understand what you tested to get above output.

**Comment by nirik** [comment]
We installed a z/vm fedora 35 instance. It was configured to have the needed s390x config and worked fine. 
We later started setting it's network config via linux-system-roles/network. 

We are using rhel-system-roles-1.7.3-2.el8.noarch
We are passing the following connections:

```
network_connections:
  - autoconnect: yes
    ip:
      address:
        - "{{ enc900_ipv4_ip }}/{{ enc900_ipv4_nm }}"
      dhcp4: no
      dns:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      dns_search:
        - "{{ dns_search1 }}"
        - "{{ dns_search2 }}"
      gateway4: "{{ enc900_ipv4_gw }}"
    mac: "{{ ansible_default_ipv4.macaddress }}"
    name: enc900
    state: up
    type: ethernet
```

and the following vars:

```
dns1: 10.3.163.33
dns2: 10.3.163.34
dns_search1: "iad2.fedoraproject.org"
dns_search2: "fedoraproject.org"
enc900_ipv4_gw: 10.16.0.254
enc900_ipv4_nm: 24
enc900_ipv4_ip: 10.16.0.11
```

Running that all seemed fine. Then we later rebooted and had no network device. So, the 3 additional lines needed for s390x were gone. 

So, I suppose this is just a case of us not knowing that s390x wasn't supported, but perhaps a check could be added if removing those options to warn the user that it may result in problems on s390x if they were set in old confirg but not new?

Are there any plans for s390x support?
