### ISSUE TITLE
Routing rules cannot refer to routing tables by name

### ISSUE THREAD

**Issue by bsteinb** [linux-system-roles/network#506]
Thank you for adding support for routing rules. The feature is working well for us. However, as it is, it does not support referring to routing tables by name, only by their numerical id, e.g.:

```yaml
      routing_rule:
        - priority: 99
          family: ipv4
          iif: eno1
          action: to-table
          table: main
```

results in task "Configure networking connection profiles" to fail with:

```
  msg: 'fatal error: Must be number, not str'
```

while it works with `table: 254`.

It is possible to refer to tables by name when specifying ordinary routes on an interface (`ip.routes.table`) and indeed both code paths use `ArgValidatorRouteTable` to validate the `table` value, which does allow `int` or `str`. However, that validator class does not normalize the value to `number` by looking up the mapping. That happens later in `ArgValidator_ListConnections.validate_route_tables` which only works on tables specified as part of ordinary routes, not on routing rules. Either this method `validate_route_tables` should be modified to also normalize tables specified as part of routing rules or maybe the normalization can be moved into `ArgValidatorRouteTable`.
