### ISSUE TITLE
network_state functionality doesn't appear to be idempotent

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/network#519]
When using the "network_state" functionality, it doesn't appear to be idempotent

Example playbook:

```
- name: Configure DNS
  hosts: all
  tasks:
    - name: Configure DNS
      import_role:
        name: /tmp/network
      vars:
        network_state:
          dns-resolver:
            config:
              server:
                - 192.168.0.2
```

Playbook reports "Configure networking state" task as changed every time when run.  This is on a Fedora 36 host.
