### ISSUE TITLE
How to keep existing profile name

### ISSUE THREAD

**Issue by ts97783** [linux-system-roles/network#601]
Hi, 

We're provisioning physical hosts on a single interface (eno1). Then run a post build ansible task to create a bond. 

Using the below network_connections creates bond0 as expected with eno1 and eno2 slaves. However, we now have ifcfg-eno1-1 (new slave profile) and ifcfg-eno1 (original profile). We do not want ifcfg-eno1-1. How can we retain the original profile name ifcfg-eno1 for the slave? 

```
# ls -x1 /etc/sysconfig/network-scripts/*eno1*
/etc/sysconfig/network-scripts/ifcfg-eno1
/etc/sysconfig/network-scripts/ifcfg-eno1-1
```

```
      - name: bond0
        type: bond
        interface_name: bond0
        ip:
          address:
            - "10.140.4.135/28"
          gateway4: "10.140.4.129"
        state: up

      - name: eno1
        interface_name: eno1
        type: ethernet
        controller: bond0
        state: up

      - name: eno2
        interface_name: eno2
        type: ethernet
        controller: bond0
        state: up
```

I've tried using network_state, which does not create the new profile ifcfg-eno1-1 (desired outcome). However it seems network_state does not support the gateway4 parameter for interfaces. So, instead we need a routes section in the play which then creates a route-bond0 file in /etc/sysconfig/network-scripts/.

```
      routes:
        config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.140.4.129
          next-hop-interface: bond0
      interfaces:
        - name: bond0
          type: bond
          state: up
          ipv4:
            address:
            - ip: 10.140.4.135
              prefix-length: 28
            enabled: true
          link-aggregation:
            mode: active-backup
            options:
              primary: eno1
            port:
            - eno1
            - eno2
```

The expected outcome is to only have ifcfg-bond0, ifcfg-eno1 and ifcfg-eno2 with a gateway defined for bond0. Is there a way to achieve this? 

I appreciate ifcfg files are now legacy, but we have a lot of in-house tasks that rely on them for now. 

Thanks!
