### ISSUE TITLE
network_state should not change IPv6 state when not configured

### ISSUE THREAD

**Issue by myllynen** [linux-system-roles/network#614]
Using this definition against RHEL 8.8 systems which use NM and ifcfg files

```
    network_state:
      dns-resolver:
        config:
          server:
            - 1.1.1.1
      interfaces:
        - name: net0
          type: ethernet
          state: up
          ipv4:
            enabled: true
            auto-dns: false
            dhcp: true
```

changes `IPV6_INIT=no` to `IPV6_INIT=yes` on IPv4-only systems. On RHEL 9.2 systems which use NM and nmconnection files this does not happen, which is expected. The workaround is of course obvious but nevertheless network_state should not change anything outside of the provided configuration definition. Thanks.
