### ISSUE TITLE
Question Changing the IP of the remote host

### ISSUE THREAD

**Issue by FH089** [linux-system-roles/network#615]
I have a golden image on my hypervisor, i clone the image to a new VM everytime i need one. The ip configuration of the new machine is static. 

I'm trying to set a new IP Address via ansible. My host_vars looks like this

```yaml 
network_connections:
  - name: Wired0
    type: ethernet
    interface_name: eth0
     ip:
      address:
        - 192.168.1.33/24

```

to deploy the new configuration i run this command.

```bash

ansible-playbook -l myhostname -e "ansible_host=192.168.1.12"

``` 

The command "stops" at the task "Configure networking connection profiles". After clicking ctrl + c i'm able to ssh in to the machine with the "new" ip address. Im assuming ansible try to talk with the "old" ip address. 

Is there any way to fix this behaviour or do it in a better way? 

ansible newbie btw.
