### ISSUE TITLE
ipv4.dns-data: unknown property (7)

### ISSUE THREAD

**Issue by EliasBoulharts** [linux-system-roles/network#616]
I got an error when dns are setup with my IP.

# Environment
OS: rocky linux 9.1
linux-system-roles.network: 1.11.4
ansible core: 2.13.7

# Input
``` yaml
network_connections:
  - name: ens192
    interface_name: ens192
    type: ethernet
    state: up
    ip:
      address: XXX.XXX.XXX.XXX/XX
      gateway4: XXX.XXX.XXX.XXX
      dns:
        - XXX.XXX.XXX.XXX
        - XXX.XXX.XXX.XXX
  - name: ens224
    interface_name: ens224
    type: ethernet
    state: up
    ip:
      address: XXX.XXX.XXX.XXX/XX
      route:
        - network: XXX.XXX.XXX.XXX
          prefix: 16
          gateway: XXX.XXX.XXX.XXX
```
# Error
``` json
fatal: [myfqdn.domain]: FAILED! => 
{
    "_invocation": {
        "module_args": {
            "__debug_flags": "",
            "__header": "#\n# Ansible managed\n#\n",
            "connections": [
                {
                    "interface_name": "ens192",
                    "ip": {
                        "address": "XXX.XXX.XXX.XXX/XX",
                        "dns": [
                            "XXX.XXX.XXX.XXX",
                            "XXX.XXX.XXX.XXX"
                        ],
                        "gateway4": "XXX.XXX.XXX.XXX"
                    },
                    "name": "ens192",
                    "state": "up",
                    "type": "ethernet"
                },
                {
                    "interface_name": "ens224",
                    "ip": {
                        "address": "XXX.XXX.XXX.XXX/XX",
                        "route": [
                            {
                                "gateway": "XXX.XXX.XXX.XXX",
                                "network": "XXX.XXX.XXX.XXX",
                                "prefix": XX
                            }
                        ]
                    },
                    "name": "ens224",
                    "state": "up",
                    "type": "ethernet"
                }
            ],
            "force_state_change": false,
            "ignore_errors": false,
            "provider": "nm"
        }
    },
    "changed": true,
    "msg": "error: updating connection failed: failure to update connection: nm-connection-error-quark: ipv4.dns-data: unknown property (7)",
    "stderr": "[005] <info>  #0, state:up persistent_state:present, 'ens192': update connection ens192, 407efcd8-c896-41d0-81da-3bca2644272f\n[006] <error> #0, state:up persistent_state:present, 'ens192': updating connection failed: failure to update connection: nm-connection-error-quark: ipv4.dns-data: unknown property (7)\n",
    "stderr_lines": [
        "[005] <info>  #0, state:up persistent_state:present, 'ens192': update connection ens192, 407efcd8-c896-41d0-81da-3bca2644272f",
        "[006] <error> #0, state:up persistent_state:present, 'ens192': updating connection failed: failure to update connection: nm-connection-error-quark: ipv4.dns-data: unknown property (7)"
    ]
}
```
