### ISSUE TITLE
not idempotent

### ISSUE THREAD

**Issue by emyr666** [linux-system-roles/network#689]
It keeps saying

TASK [network : Configure networking connection profiles] **********************
changed: [hostname]

Every time I run the playbook but nothing has changed.

This is the network role section. The template vars come from the host_vars files for each host.

```
    - role: network
      network_connections:
      - name: ens18
        type: ethernet
        autoconnect: true
        mac: "{{ pxe_mac }}"
        ip:
          dhcp4: true
      - name: ens19
        type: ethernet
        autoconnect: true
        mac: "{{ fast_mac }}"
        ip:
          dhcp4: false
          dhcp4: false
          gateway4: 10.21.0.253
          address:
          - "{{ fast_ip }}/16"
      - persistent_state: absent
```
