### ISSUE TITLE
network - state:absent followed by state:up only works part of time

### ISSUE THREAD

**Issue by hartsjc** [linux-system-roles/network#7]
```
# cat network.yml 
---
- hosts: host.domain.com
  vars:
    network_connections:
      - name: enp5s0f0
        state: absent
      - name: enp5s0f0
        interface_name: enp5s0f0
        type: ethernet
        state: up
        autoconnect: yes
        ip:
          dhcp4: no
          auto6: no
          address:
            - 10.0.0.1/30
  roles:
    - role: network 
# ansible-playbook -l host.domain.com network.yml 
```

Working output:

> TASK [network : Configure networking connection profiles] *************************************************************************
>  [WARNING]: <info>  #0, state:absent, "enp5s0f0": delete connection enp5s0f0, 51292573-07da-4146-9b06-954f52a5f8d9
>  [WARNING]: <info>  #1, state:up, "enp5s0f0": add connection enp5s0f0, 51292573-07da-4146-9b06-954f52a5f8d9
>  [WARNING]: <info>  #1, state:up, "enp5s0f0": up connection enp5s0f0, 51292573-07da-4146-9b06-954f52a5f8d9

Failing output:

> TASK [network : Configure networking connection profiles] *************************************************************************
> TASK [network : Configure networking connection profiles]
>  [WARNING]: <info>  #0, state:absent, "enp5s0f0": delete connection enp5s0f0, 6d2a7eff-eadb-45c4-8c4c-6d2add08ede9
>  [WARNING]: <info>  #1, state:up, "enp5s0f0": add connection enp5s0f0, 6d2a7eff-eadb-45c4-8c4c-6d2add08ede9
>  [WARNING]: <info>  #1, state:up, "enp5s0f0": up connection enp5s0f0, 6d2a7eff-eadb-45c4-8c4c-6d2add08ede9
>  [WARNING]: <warn>  #1, state:up, "enp5s0f0": failure: 'ActiveConnection' object has no attribute 'get_state_reason' [[Traceback (most recent call last):   File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 1776, in run     self.run_state_up(idx)
> File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 1942, in run_state_up     self.nmutil.connection_activate_wait(ac, wait_time)   File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 1498, in connection_activate_wait     complete,
> failure_reason = check_activated(ac, dev)   File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 1468, in check_activated     ac_reason = ac.get_state_reason() AttributeError: 'ActiveConnection' object has no attribute 'get_state_reason' ]]
>  [WARNING]: exception: Traceback (most recent call last):   File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 2103, in <module>     Cmd.create().run()   File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 1776, in run
> self.run_state_up(idx)   File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 1942, in run_state_up     self.nmutil.connection_activate_wait(ac, wait_time)   File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 1498, in
> connection_activate_wait     complete, failure_reason = check_activated(ac, dev)   File "/tmp/ansible_xWURw9/ansible_module_network_connections.py", line 1468, in check_activated     ac_reason = ac.get_state_reason() AttributeError: 'ActiveConnection' object has no
> attribute 'get_state_reason'
> 
> fatal: [host.domain.com]: FAILED! => {"changed": false, "failed": true, "msg": "fatal error: 'ActiveConnection' object has no attribute 'get_state_reason'"}
> 	to retry, use: --limit @/usr/local/ansible/network.retry

Hardware configureing
```
# lspci
05:00.0 Ethernet controller: Mellanox Technologies MT27700 Family [ConnectX-4]

# ethtool enp5s0f0
Settings for enp5s0f0:
	Supported ports: [ FIBRE ]
	Supported pause frame use: Symmetric Receive-only
	Supports auto-negotiation: No
	Advertised pause frame use: No
	Advertised auto-negotiation: No
	Speed: 100000Mb/s
	Duplex: Full
	Port: Direct Attach Copper
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: off
	Supports Wake-on: d
	Wake-on: d
	Link detected: yes
```
