### ISSUE TITLE
Add ability to adjust mulitcast settings on a network bridge

### ISSUE THREAD

**Issue by steven-ellis** [linux-system-roles/network#729]
When creating a bridge you need to adjust some of the multicast settings for service discovery like ssdp to work correctly

```
nmcli connection modify br0 bridge.multicast-snooping on
nmcli connection modify br0 bridge.multicast-querier on
```

The YAML could look something like

```
        bridge:
           multicast-snooping: true
           multicast-querier: true
```

**Comment by liangwen12year** [comment]
The multicast settings on the network bridge are already supported in `network_state` variable, you can take a look here:

Here is an example for specifying it: 

```
  - name: Set the multicast settings using network_state
    vars:
      network_state:
        interfaces:
        - name: br0
          type: linux-bridge
          state: up
          bridge:
            options:
              multicast-querier: true
              multicast-snooping: true
    ansible.builtin.include_role:
      name: linux-system-roles.network
``` 

If you are interested in other multicast settings, you can take a look here, https://nmstate.io/devel/yaml_api.html#linux-bridge-interface.
