### ISSUE TITLE
Allow to set ipv4.may-fail / ipv6.may-fail

### ISSUE THREAD

**Issue by Hoeze** [linux-system-roles/network#735]
Hi, I am trying to setup a persistent bridge with networkmanager but the bridge connection gets deactivated once it fails to configure IPv4.
Networkmanager allows to set "ipv4.may-fail" and "ipv6.may-fail" to keep the connection up even when the ip configuration fails.
Is it possible to set these options with this role?
If not, would it be possible to add these options?

**Comment by Hoeze** [comment]
I just realized that this is the wrong setting to change.
What I actually would need to keep the device up is setting `connection.autoconnect-retries=0`.

**Comment by liangwen12year** [comment]
In NetworkManager, `ipv4.may-fail`  allows the connection to remain active even if it fails to configure an IP address (e.g., if IPv4 configuration fails). When may-fail is set to yes, NetworkManager will not deactivate the connection due to IP configuration failure. If your goal is to keep the bridge connection active even when IPv4 fails, setting may-fail to yes is the more appropriate solution. If you need NetworkManager to keep retrying until it successfully configures IPv4, you can use `autoconnect-retries` with an appropriate value. We can support the `connection.autoconnect-retries` in the network role, I will implement it asap, but if you would like to implement this feature, patch is welcomed.

**Comment by liangwen12year** [comment]
The PR for supporting `autoconnect_retries` is https://github.com/linux-system-roles/network/pull/737 .

**Comment by Hoeze** [comment]
Amazing! Thanks a lot @liangwen12year  :tada: 
Given your previous answer, it would then make sense to have `ipv4.may-fail=yes` and `autoconnect_retries=0`, if I want to keep the connection up until it obtains an IP, right?

**Comment by liangwen12year** [comment]
@Hoeze , `ipv4.may-fail=yes` tells NetworkManager that the connection should still be considered "up" even if it fails to configure IPv4. In your situation, I honestly think that it would then make sense to have `ipv4.may-fail=no` and `autoconnect_retries=0`.

**Comment by Hoeze** [comment]
Oh, I see, then I misunderstood this option. Thank you for the explanation.

Would you be able to also support the `ipv[4|6].may-fail` option in this role?

**Comment by liangwen12year** [comment]
The property in `network_state` variable corresponds to `may-fail: no` is  `wait-ip`,  the setting can be set to the following options: 
```
     * "any": System will consider interface activated when any IP stack is
              configured(neither static or automatic).
     * "ipv4": System will wait IPv4 been configured.
     * "ipv6": System will wait IPv6 been configured.
     * "ipv4+ipv6": System will wait both IPv4 and IPv6 been configured.
```

Here is an example: 
```
network_state:
  interfaces:
    - name: eth1
      type: ethernet
      state: up
      wait-ip: ipv4+ipv6
      ipv4:
        enabled: true
        dhcp: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
      ipv6:
        enabled: true
        dhcp: true
        autoconf: true
        auto-dns: true
        auto-gateway: true
        auto-routes: true
```        

@Hoeze , can you try out the `network_state` variable? I think that this already fulfill your needs by configuring `wait-ip` proprety.
