### ISSUE TITLE
connections[0].ip: property is not allowed for state 'up' and persistent_state 'present'

### ISSUE THREAD

**Issue by silanea** [linux-system-roles/network#85]
Hoping that I did not misunderstand a fundamental aspect of how this role works, I encountered the following issue:

`TASK [network : Configure networking connection profiles] ***********************************************************************************************************************************************************************************
fatal: [redacted]: FAILED! => {"changed": false, "msg": "fatal error: configuration error: connections[0].ip: property is not allowed for state 'up' and persistent_state 'present'"}`

Relevant variables:

```
network_connections:
  - name: "ens3"
    state: up
    ip:
      address:
        - x.x.x.x/32
        - x:x:x::/64
```
Incidentally the specified IPs match the current system configuration, so no actual changes should be taking place anyway but it still fails. If you need any other info or logs from the system, please let me know.

Fedora 28 Server, current master (https://github.com/linux-system-roles/network/commit/a10e72b90566380ea2245c81345f62594292d1d4)

**Comment by tyll** [comment]
Thank you for the report. Currently the role requires the type to be specified to support setting the IP addresses, it works when you add `type: ethernet` to the settings:

```
- hosts: all
  vars:
    network_connections:
    - name: eth2
      state: up
      type: ethernet
      ip:
        address:
          - 192.0.2.28/32
          - 2001:db8:23:32::/64
  roles:
    - linux-system-roles.network
```

The error message could be improved, though. Making `type: ethernet` the default bears the risk of breaking configurations when the specified device is a bond device or something else.
