### ISSUE TITLE
Ansible 2.7 breaks tests

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#89]
Ansible 2.7 does not allow to specify variables when including tasks anymore, this breaks this syntax:

```
- name: Remove interfaces
  hosts: all
  tasks:
    - include_tasks: tasks/manage-test-interface.yml state=absent
```

Possible alternative is:

```
- name: Remove interfaces
  hosts: all
  tasks:
    - include_tasks: tasks/manage-test-interface.yml 
      vars:
           state: absent
```
