### ISSUE TITLE
Ability to delete and down all connection profiles for a given interface

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/network#92]
When installing rhel on a new virtual machine with 6 network interfaces, all interfaces are auto configured and activated with profile names that may or may not match the linux device name.  Because I do not want these and instead want my own connection profile names, I would like the ability to delete all configuration profiles for each network device by `mac` or `interface_name`

```
[root@rhel7 ~]# nmcli d
DEVICE  TYPE      STATE      CONNECTION 
ens10   ethernet  connected  ens10      
ens11   ethernet  connected  ens11      
ens12   ethernet  connected  ens12      
ens13   ethernet  connected  ens13      
eth4    ethernet  connected  eth2       
eth5    ethernet  connected  eth3       
lo      loopback  unmanaged  --         
```
However, this does not work:
```
        network_connections:
          - name: ens11
            #mac: "{{ hostvars[inventory_hostname].net1_mac }}"
            interface_name: "{{ hostvars[inventory_hostname].net1_dev }}"
            state: down
            persistent_state: absent
```

No matter if I use `mac` or `interface_name`, I get the following errors:

```
TASK [rhel-system-roles.network : Configure networking connection profiles] ***************
fatal: [rhel7]: FAILED! => {"changed": false, "msg": "fatal error: configuration error: connections[0].interface_name: property is not allowed for state 'down' and persistent_state 'absent'"}

```
```
TASK [rhel-system-roles.network : Configure networking connection profiles] ***************
fatal: [rhel7]: FAILED! => {"changed": false, "msg": "fatal error: configuration error: connections[0].mac: property is not allowed for state 'down' and persistent_state 'absent'"}

```
